version: '3.5'
services:
  jetty:
    build: ./
    ports:
      - 8080:8080
  mysql:
    image: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: jetty
       MYSQL_USER: jetty
       MYSQL_PASSWORD: jetty
